package main

import "fmt"

func IsEven(num int) bool {
    if (num % 2 == 0) {
        return true
    } else {
        return false
    }
}

func EvenFibonacciNumber() {
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms. sum += evenTerm
     * answer: 4613732
     */
    const MAX_TERM = 4_000_000

    prevVal := 1
    currVal := 1

    var sum int

    for ; currVal < MAX_TERM ; {
        tempPrevVal := currVal

        prevVal, currVal = tempPrevVal, prevVal + currVal

        fmt.Printf("prevVal: %d, currVal: %d, tempPrevVal: %d\n",prevVal, currVal, tempPrevVal)

        if (IsEven(currVal)) {
            sum += currVal
        }
    }

    fmt.Println(sum)
}
